### ISSUE TITLE
Lowercase sequence - No probe candidates to write to FASTA

### ISSUE THREAD

**Issue by med-ss20** [KevinKuchinski/ProbeTools#1]
Dear Kevin
First, thank you very much for this amazing tool for probes design.
I found a small bug which might improve the tool.
When you have a fasta sequence in lowercase letters, i.e.
```
>Sample_1
acgtacgtacgtacgtacgt
```
ProbeTools v0.1.9 produces no probes: No probe candidates to write to FASTA.
With uppercase fasta sequence everything works perfect.
```
>Sample_1
ACTGACTGACTGACTGT
```

Thank you!
Kind regards,
Sviat

```
$ probetools makeprobes -t lowercase.fasta -b 100 -o lowercase

ProbeTools MakeProbes v0.1.9
https://github.com/KevinKuchinski/ProbeTools

Extracting target names and seqs from lowercase.fasta...
 Total targets loaded: 56

******************** ROUND 1 ********************

Extracting low coverage areas...
 Wrote 56 low coverage seqs from 56 targets.

Enumerating all 120-mers in ./lowercase_low_cov_seqs.fa...
 Loaded 56 target seqs in ./lowercase_low_cov_seqs.fa...
 Enumerated 0 k-mers from ./lowercase_low_cov_seqs.fa.
 Clustering k-mers at 90% identity...
 K-mer clustering finished.
Removing any previously designed probes...
 Loaded 0 previously designed probes in ./lowercase_probes.fa
Ranking probe candidates...
 Loaded 0 probe candidates.
Writing top probe candidates to ./lowercase_round_1_probes.fa...
 No probe candidates to write to FASTA.

Incremental probe design finished.
 No additional probes could be designed.

Writing capture results to ./lowercase_capture.pt...
Writing capture results to ./lowercase_capture.pt...
 Wrote capture results for 56 targets.
Writing probe coverage and probe depth summary stats to ./lowercase_summary_stats_report.tsv...
Writing probe coverage and probe depth stats for each target to ./lowercase_long_stats_report.tsv...

Done.


```

**Comment by KevinKuchinski** [comment]
Hello Sviat,

Thanks for getting in touch, and I'm glad to hear ProbeTools is helping with your projects. The issue you have flagged arises because lower base bases are conventionally used to mask repetitive and low-complexity sequences that cause problems for clustering and alignment algorithms:
https://www.drive5.com/usearch/manual/masking.html
https://blast.ncbi.nlm.nih.gov/doc/blast-help/FAQ.html
Consequently, sequences written in lower case were treated as if they are masked, and were thus ignored.

I have updated ProbeTools (v0.1.11) to address the issue. The makeprobes and clusterkmers modules now convert k-mers to uppercase sequences when they are enumerated. The getlowcov module converts low coverage sub-sequences to uppercase. The stats module counts lowercase bases as their corresponding uppercase base.

Thanks for bringing this issue to my attention, and good luck with your capture projects!
